sudo: false
language: ruby
rvm:
- 2.1.9
- 2.2.5
- 2.3.1
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
env:
  global:
  - JRUBY_OPTS=--debug
cache: bundler
bundler_args: "--without development --jobs 7"
script: bundle exec rake spec
addons:
    code_climate:
        repo_token: 4a6f104d1ad380cefa6b120cbdef76640ce1630f53effa35bdf15f18973a9f25
